### ISSUE TITLE
Conteo de "likes"

### ISSUE THREAD

**Issue by yajedev** [yajepanta/maqay-agenda-ambiental#1]
- [ ] Revisar opciones para almacenar "like" y que se pueda consumir un reporte de los likes:
Wordpress / Google Sheets / Firebase

- [ ] Revisar opciones para que se pueda dar like una sola vez:
Autenticar con Google / Almacenar en LocalStorage

**Comment by unjust** [comment]
Para almanecer:
https://developers.google.com/sheets/api/guides/values#writing
https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/

**Comment by unjust** [comment]
Justo vi que los share buttons estan usando `react-share` - si queremos usar el authenticacion de este arremienta, no estoy segura como usarla. Para algo mas rapido creo podemos experimentar con `LocalStorage` para version 1 y almacenar en Google Sheets.

https://stackoverflow.com/a/9949361/274949
