### ISSUE TITLE
URL personalizada para cada post

### ISSUE THREAD

**Issue by yajedev** [yajepanta/maqay-agenda-ambiental#3]
- [ ] Al momento de compartir en redes sociales, cada post/propuesta debe tener un link personalizado.

**Comment by unjust** [comment]
Tambien con meta tags para tener contenido rico
https://css-tricks.com/essential-meta-tags-social-media/

**Comment by yajedev** [comment]
Solucionado con React Share que comparte la url pero de cada categoría. Ej: Si entramos a Tema ambiental/ Cambio climático, y queremos compartir un post, compartirá la ruta general.
